{
 "title": "Solar Monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Energy Produced",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "production_date",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    max(energy) as Wh\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 30) * 30) * 1000 as t,\n    max(energy) as Wh\nFROM default.solar_production\n\nWHERE production_date >= toDate(1656312913) AND production_date <= toDate(1656399313) AND timestamp >= toDateTime(1656312913) AND timestamp <= toDateTime(1656399313)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "solar_production"
    }
   ]
  },
  {
   "title": "Energy Generated in $",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 0 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "database": "default",
     "dateColDataType": "production_date",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    max(energy * schedule.price_cents/100.0)/1000.0 as price\nFROM $table\njoin schedule on MONTH(solar_production.timestamp) = schedule.months\nand DAYOFWEEK(solar_production.timestamp) = schedule.days\nand HOUR(solar_production.timestamp) = schedule.hours\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 as t,\n    max(energy * schedule.price_cents/100.0)/1000.0 as price\nFROM default.solar_production\njoin schedule on MONTH(solar_production.timestamp) = schedule.months\nand DAYOFWEEK(solar_production.timestamp) = schedule.days\nand HOUR(solar_production.timestamp) = schedule.hours\n\nWHERE production_date >= toDate(1655796160) AND production_date <= toDate(1656400960) AND timestamp >= toDateTime(1655796160) AND timestamp <= toDateTime(1656400960)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "solar_production"
    }
   ]
  },
  {
   "title": "Devices reporting",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "production_date",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    max(devices_reporting)\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1200) * 1200) * 1000 as t,\n    max(devices_reporting)\nFROM default.solar_production\n\nWHERE production_date >= toDate(1655796613) AND production_date <= toDate(1656401413) AND timestamp >= toDateTime(1655796613) AND timestamp <= toDateTime(1656401413)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "solar_production"
    }
   ]
  },
  {
   "title": "Energy Production",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "production_date",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    max(energy) as Wh\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 as t,\n    max(energy) as Wh\nFROM default.solar_production\n\nWHERE production_date >= toDate(1655794856) AND production_date <= toDate(1656399656) AND timestamp >= toDateTime(1655794856) AND timestamp <= toDateTime(1656399656)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "solar_production"
    },
    {
     "database": "default",
     "dateColDataType": "production_date",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    ($timeSeries) + (86400 * 1000) as t,\n    max(energy) as yesterday_Wh\nFROM $table\n\nWHERE production_date >= toDate(($__from/1000) - 86400) AND production_date <= toDate(($__to/1000) - 86400) AND timestamp >= toDateTime(($__from/1000) - 86400) AND timestamp <= toDateTime(($__to/1000) - 86400)\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    ((intDiv(toUInt32(timestamp), 300) * 300) * 1000) + (86400 * 1000) as t,\n    max(energy) as yesterday_Wh\nFROM default.solar_production\n\nWHERE production_date >= toDate((1655794830634/1000) - 86400) AND production_date <= toDate((1656399630635/1000) - 86400) AND timestamp >= toDateTime((1655794830634/1000) - 86400) AND timestamp <= toDateTime((1656399630635/1000) - 86400)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "solar_production"
    }
   ]
  },
  {
   "title": "Power Production",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "production_date",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    max(power) as watts\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 30) * 30) * 1000 as t,\n    max(power) as watts\nFROM default.solar_production\n\nWHERE production_date >= toDate(1656313107) AND production_date <= toDate(1656399507) AND timestamp >= toDateTime(1656313107) AND timestamp <= toDateTime(1656399507)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "solar_production"
    },
    {
     "database": "default",
     "dateColDataType": "production_date",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    ($timeSeries) + (86400 * 1000) as t,\n    max(power) as yesterday_watts\nFROM $table\n\nWHERE production_date >= toDate(($__from/1000) - 86400) AND production_date <= toDate(($__to/1000) - 86400) AND timestamp >= toDateTime(($__from/1000) - 86400) AND timestamp <= toDateTime(($__to/1000) - 86400)\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    ((intDiv(toUInt32(timestamp), 30) * 30) * 1000) + (86400 * 1000) as t,\n    max(power) as yesterday_watts\nFROM default.solar_production\n\nWHERE production_date >= toDate((1656313038859/1000) - 86400) AND production_date <= toDate((1656399438859/1000) - 86400) AND timestamp >= toDateTime((1656313038859/1000) - 86400) AND timestamp <= toDateTime((1656399438859/1000) - 86400)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "solar_production"
    }
   ]
  },
  {
   "title": "Energy Generated in $",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "production_date",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    max(energy * schedule.price_cents/100.0)/1000.0 as price\nFROM $table\njoin schedule on MONTH(solar_production.timestamp) = schedule.months\nand DAYOFWEEK(solar_production.timestamp) = schedule.days\nand HOUR(solar_production.timestamp) = schedule.hours\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 120) * 120) * 1000 as t,\n    max(energy * schedule.price_cents/100.0)/1000.0 as price\nFROM default.solar_production\njoin schedule on MONTH(solar_production.timestamp) = schedule.months\nand DAYOFWEEK(solar_production.timestamp) = schedule.days\nand HOUR(solar_production.timestamp) = schedule.hours\n\nWHERE production_date >= toDate(1655796166) AND production_date <= toDate(1656400966) AND timestamp >= toDateTime(1655796166) AND timestamp <= toDateTime(1656400966)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "solar_production"
    }
   ]
  }
 ]
}